version: '2'
services: 
  api_devfestne17_torproxy:
    restart: always
    image: dperson/torproxy
    container_name: "api_devfestne17_torproxy"
    ports:
      - "8118:8118"
      - "9050:9050" 
  api_devfestne17_backend:
    restart: always
    build: ./.
    ports:
      - "8888:8888"
    container_name: "api_devfestne17_backend"
    volumes:
      - ../:/app
    depends_on:
      - api_devfestne17_torproxy
      - api_devfestne17_mongo
  api_devfestne17_mongo:
    image: mongo
    container_name: "api_devfestne17_mongo"
    ports:
      - "27017:27017"